name: Build JARs

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: JARs
        path: /home/runner/work/SpigotFiles/SpigotFiles/target/*.jar
        retention-days: 7

    - name: Remove File
      uses: JesseTG/rm@v1.0.3
      with:
        path: /home/runner/work/SpigotFiles/SpigotFiles/.gitignore

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: build
        push_options: '--force'
        skip_checkout: true
